### ISSUE TITLE
WARNING!!!!!!!

### ISSUE THREAD

**Issue by ghost** [siriusdevs/rpm-hws_7-2_2023#1]
![image](https://user-images.githubusercontent.com/113104983/224009242-66122f00-fd05-4c7f-86ea-254fc6c32b11.png)

**Comment by kolenka8** [comment]
![image](https://user-images.githubusercontent.com/113104983/224009578-c849cbb0-074c-4759-9f3d-d45971be1cbd.png)

**Comment by DNS-denis** [comment]
удалииии

**Comment by kolenka8** [comment]
![image](https://user-images.githubusercontent.com/113104983/224010463-9d2bd233-ccb1-426a-9957-47e83502a8e7.png)

**Comment by siriusdevs** [comment]
wtf
